
  <script async src="//cdn.jsdelivr.net/gh/zxiaosi/cdn/Hexo/js/fireworks.js"></script>

  <canvas class="fireworks" style="position: fixed;left: 0;top: 0;z-index: 1; pointer-events: none;" ></canvas>
  <script src="//cdn.bootcss.com/animejs/2.2.0/anime.min.js"></script>
  <script async src="//cdn.jsdelivr.net/gh/zxiaosi/cdn/Hexo/js/explosion.js"></script>

  <script async src="//cdn.jsdelivr.net/gh/zxiaosi/cdn/Hexo/js/love.js"></script>
